/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VibeRouteImport } from './routes/vibe'
import { Route as SpotifyCallbackRouteImport } from './routes/spotify-callback'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetIdRouteImport } from './routes/set.$id'

const VibeRoute = VibeRouteImport.update({
  id: '/vibe',
  path: '/vibe',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: '/spotify-callback',
  path: '/spotify-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetIdRoute = SetIdRouteImport.update({
  id: '/set/$id',
  path: '/set/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
  '/vibe': typeof VibeRoute
  '/set/$id': typeof SetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
  '/vibe': typeof VibeRoute
  '/set/$id': typeof SetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
  '/vibe': typeof VibeRoute
  '/set/$id': typeof SetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/library'
    | '/spotify-callback'
    | '/vibe'
    | '/set/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/library'
    | '/spotify-callback'
    | '/vibe'
    | '/set/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/library'
    | '/spotify-callback'
    | '/vibe'
    | '/set/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  LibraryRoute: typeof LibraryRoute
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
  VibeRoute: typeof VibeRoute
  SetIdRoute: typeof SetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vibe': {
      id: '/vibe'
      path: '/vibe'
      fullPath: '/vibe'
      preLoaderRoute: typeof VibeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify-callback': {
      id: '/spotify-callback'
      path: '/spotify-callback'
      fullPath: '/spotify-callback'
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set/$id': {
      id: '/set/$id'
      path: '/set/$id'
      fullPath: '/set/$id'
      preLoaderRoute: typeof SetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  LibraryRoute: LibraryRoute,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
  VibeRoute: VibeRoute,
  SetIdRoute: SetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
